#!/bin/bash

# Additional Requirements
#  bash: To run this script
#  hostapd: To host a wireless hotspot
#  haveged: To collect entropy and feed into random pool
#  macchanger: To change mac of wireless interface

if [ $1 = "-h" -o $1 = "--help" ]
	then
	echo "Wich script by Roach"
	echo "	Usage wich [OPTIONS] {PERAMETERS}"
	echo "		-1 or --man :	Put Into Managed Mode"
	echo "		-2 or --mon :	Put Into Monitor Mode"
	echo "		-3 or --mas :	Put Into Master Mode ('Wich --mas --help' For More Info)"
	echo "		-4 or --stop :	Stop Hosted AP ('wich --mas --help' For More Info)"
	echo "		-5 or --creds : To Capture Credentials On LAN ('wich --creds --help' For More Info)"
	echo "		-6 or --wifijam : To Jam All Wifi Signals In Range ('wich --wifijam --help' For More Info)"
	echo "		-h or --help :	To Show This Help Test"
	echo "		--use :	Show Usage"
else
	if [ $1 = "-1" -o $1 = "--man" ]
		then
		ifconfig $2 down
		macchanger -r $2
		iwconfig $2 mode managed
		ifconfig $2 up
		tput bold
		echo "Managed mode enabled on $2"
	elif [ $1 = "-2" -o $1 = "--mon" ]
		then
		ifconfig $2 down
		macchanger -r $2
		iwconfig $2 mode monitor
		ifconfig $2 up
		tput bold
		echo "Monitor mode enabled on $2"
	elif [ $1 = "-3" -o $1 = "--mas" ]
		then
		/usr/sbin/create_ap --daemon $2 $3 $4 $5 $6 $7 $8 $9
		tput bold
		echo "Master mode enabled on $2"
	elif [ $1 = "-4" -o $1 = "--stop" ]
		then
		/usr/sbin/create_ap --stop $2 $3
	elif [ $1 = "-5" -o $1 = "--creds" ]
		then
		/usr/sbin/creds $2 $3 $4 $5 $6 $7 $8 $9
	elif [ $1 = "-6" -o $1 = "--wifijam" ]
		then
		/usr/sbin/wifijammer $2 $3 $4 $5 $6 $7 $8 $9
	elif [ $1 = "--use" ]
		then
		echo "To put into managed mode ...wich -1 'interface name'"
		echo "To put into monitor mode ...wich -2 'interface name'"
		echo "To put into master mode ...wich -3 'interface name' 'interface name' 'essid' 'password'"
		echo "To stop hosted AP ...wich -4 'hosted interface name'"
		echo "To capture credentials ...wich -5 -i 'interface name'"
		echo "To jam wifi networks ...wich -6 -i 'interface name'"
	fi
fi